#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from editor.ui on Tue Nov 22 21:18:52 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 209)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pidLabel = QtGui.QLabel(Form)
        self.pidLabel.setObjectName("pidLabel")
        self.verticalLayout.addWidget(self.pidLabel)
        self.pid = QtGui.QLineEdit(Form)
        self.pid.setObjectName("pid")
        self.verticalLayout.addWidget(self.pid)
        self.nameLabel = QtGui.QLabel(Form)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.name = QtGui.QLineEdit(Form)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.phoneLabel = QtGui.QLabel(Form)
        self.phoneLabel.setObjectName("phoneLabel")
        self.verticalLayout.addWidget(self.phoneLabel)
        self.phone = QtGui.QLineEdit(Form)
        self.phone.setObjectName("phone")
        self.verticalLayout.addWidget(self.phone)
        self.buttonBox = QtGui.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.actionEdit_provider = QtGui.QAction(Form)
        self.actionEdit_provider.setObjectName("actionEdit_provider")

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Form.save)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Form.cancel)
        QtCore.QObject.connect(self.pid, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.name, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.phone, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.pidLabel.setText(kdecore.i18n("ID:"))
        self.nameLabel.setText(kdecore.i18n("Nome:"))
        self.phoneLabel.setText(kdecore.i18n("Telefone:"))
        self.actionEdit_provider.setText(kdecore.i18n("Edit_provider"))
        self.actionEdit_provider.setToolTip(kdecore.i18n("Editar fornecedor"))
        self.actionEdit_provider.setShortcut(kdecore.i18n("Ctrl+E"))

