#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from window.ui on Thu Nov 17 14:40:26 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 496)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.list = QtGui.QTreeWidget(self.splitter)
        self.list.setTabKeyNavigation(True)
        self.list.setAlternatingRowColors(True)
        self.list.setItemsExpandable(False)
        self.list.setExpandsOnDoubleClick(False)
        self.list.setObjectName("list")
        self.editor = editor(self.splitter)
        self.editor.setObjectName("editor")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionDelete_Provider = QtGui.QAction(MainWindow)
        self.actionDelete_Provider.setObjectName("actionDelete_Provider")
        self.actionNew_Provider = QtGui.QAction(MainWindow)
        self.actionNew_Provider.setObjectName("actionNew_Provider")
        self.menuMenu.addAction(self.actionNew_Provider)
        self.menuMenu.addAction(self.actionDelete_Provider)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.toolBar.addAction(self.actionNew_Provider)
        self.toolBar.addAction(self.actionDelete_Provider)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(kdecore.i18n("PharmaCC"))
        self.list.setSortingEnabled(True)
        self.list.headerItem().setText(0, kdecore.i18n("Id"))
        self.list.headerItem().setText(1, kdecore.i18n("Nome"))
        self.list.headerItem().setText(2, kdecore.i18n("Telefone"))
        self.menuMenu.setTitle(kdecore.i18n("menu"))
        self.toolBar.setWindowTitle(kdecore.i18n("toolBar"))
        self.actionDelete_Provider.setText(kdecore.i18n("Apagar fornecedor"))
        self.actionDelete_Provider.setToolTip(kdecore.i18n("Apaga o fornecedor selecionado"))
        self.actionDelete_Provider.setShortcut(kdecore.i18n("Del"))
        self.actionNew_Provider.setText(kdecore.i18n("Novo fornecedor"))
        self.actionNew_Provider.setToolTip(kdecore.i18n("Cadastrar novo fornecedor"))
        self.actionNew_Provider.setShortcut(kdecore.i18n("Ctrl+N"))

from editor import editor
