#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from productIndex.ui on Thu Nov 24 16:04:33 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 599)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 711, 581))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 318, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botton_new = QtGui.QPushButton(self.layoutWidget)
        self.botton_new.setObjectName("botton_new")
        self.horizontalLayout.addWidget(self.botton_new)
        self.button_edit = QtGui.QPushButton(self.layoutWidget)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.button_delete = QtGui.QPushButton(self.layoutWidget)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.list = QtGui.QTreeWidget(self.widget)
        self.list.setGeometry(QtCore.QRect(9, 44, 691, 241))
        self.list.setTabKeyNavigation(True)
        self.list.setAlternatingRowColors(True)
        self.list.setItemsExpandable(False)
        self.list.setExpandsOnDoubleClick(False)
        self.list.setObjectName("list")
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(9, 297, 693, 281))
        self.widget_2.setObjectName("widget_2")
        self.actionNew_Product = QtGui.QAction(Form)
        self.actionNew_Product.setObjectName("actionNew_Product")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.botton_new.setText(kdecore.i18n("Novo Produto"))
        self.button_edit.setText(kdecore.i18n("Apagar Produto"))
        self.button_delete.setText(kdecore.i18n("Editar Produto"))
        self.list.setSortingEnabled(True)
        self.list.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.list.headerItem().setText(1, kdecore.i18n("Nome"))
        self.list.headerItem().setText(2, kdecore.i18n("Fornecedor"))
        self.list.headerItem().setText(3, kdecore.i18n("Preco"))
        self.list.headerItem().setText(4, kdecore.i18n("Quantidade"))
        self.actionNew_Product.setText(kdecore.i18n("Novo produto"))
        self.actionNew_Product.setShortcut(kdecore.i18n("Ctrl+N"))

