#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from productIndex.ui on Thu Nov 24 20:01:07 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 683)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botton_new = QtGui.QPushButton(Form)
        self.botton_new.setObjectName("botton_new")
        self.horizontalLayout.addWidget(self.botton_new)
        self.button_edit = QtGui.QPushButton(Form)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.button_delete = QtGui.QPushButton(Form)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.list_2 = QtGui.QTreeWidget(self.splitter)
        self.list_2.setTabKeyNavigation(True)
        self.list_2.setAlternatingRowColors(True)
        self.list_2.setItemsExpandable(False)
        self.list_2.setExpandsOnDoubleClick(False)
        self.list_2.setObjectName("list_2")
        self.product_form = ProductForm(self.splitter)
        self.product_form.setObjectName("product_form")
        self.verticalLayout.addWidget(self.splitter)
        self.actionNew_Product = QtGui.QAction(Form)
        self.actionNew_Product.setObjectName("actionNew_Product")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.botton_new.setText(kdecore.i18n("Novo Produto"))
        self.button_edit.setText(kdecore.i18n("Apagar Produto"))
        self.button_delete.setText(kdecore.i18n("Editar Produto"))
        self.list_2.setSortingEnabled(True)
        self.list_2.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.list_2.headerItem().setText(1, kdecore.i18n("Nome"))
        self.list_2.headerItem().setText(2, kdecore.i18n("Forncedor"))
        self.list_2.headerItem().setText(3, kdecore.i18n("Preco"))
        self.list_2.headerItem().setText(4, kdecore.i18n("Quantidade"))
        self.actionNew_Product.setText(kdecore.i18n("Novo produto"))
        self.actionNew_Product.setShortcut(kdecore.i18n("Ctrl+N"))

from productForm import ProductForm
