#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from productForm.ui on Thu Nov 24 16:04:32 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 368)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pidLabel = QtGui.QLabel(self.layoutWidget)
        self.pidLabel.setObjectName("pidLabel")
        self.verticalLayout.addWidget(self.pidLabel)
        self.pidText = QtGui.QLineEdit(self.layoutWidget)
        self.pidText.setObjectName("pidText")
        self.verticalLayout.addWidget(self.pidText)
        self.nameLabel = QtGui.QLabel(self.layoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameText = QtGui.QLineEdit(self.layoutWidget)
        self.nameText.setObjectName("nameText")
        self.verticalLayout.addWidget(self.nameText)
        self.fornLabel = QtGui.QLabel(self.layoutWidget)
        self.fornLabel.setObjectName("fornLabel")
        self.verticalLayout.addWidget(self.fornLabel)
        self.fornText = QtGui.QLineEdit(self.layoutWidget)
        self.fornText.setObjectName("fornText")
        self.verticalLayout.addWidget(self.fornText)
        self.priceLabel = QtGui.QLabel(self.layoutWidget)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout.addWidget(self.priceLabel)
        self.priceText = QtGui.QLineEdit(self.layoutWidget)
        self.priceText.setObjectName("priceText")
        self.verticalLayout.addWidget(self.priceText)
        self.amountLabel = QtGui.QLabel(self.layoutWidget)
        self.amountLabel.setObjectName("amountLabel")
        self.verticalLayout.addWidget(self.amountLabel)
        self.amountText = QtGui.QLineEdit(self.layoutWidget)
        self.amountText.setObjectName("amountText")
        self.verticalLayout.addWidget(self.amountText)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.pidLabel.setText(kdecore.i18n("Codigo:"))
        self.nameLabel.setText(kdecore.i18n("Nome:"))
        self.fornLabel.setText(kdecore.i18n("Fornecedor:"))
        self.priceLabel.setText(kdecore.i18n("Preco:"))
        self.amountLabel.setText(kdecore.i18n("Quantidade:"))

