#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from userForm.ui on Thu Nov 24 20:26:06 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(654, 300)
        self.formLayoutWidget = QtGui.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 631, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.lNome = QtGui.QLabel(self.formLayoutWidget)
        self.lNome.setObjectName("lNome")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lNome)
        self.leNome = QtGui.QLineEdit(self.formLayoutWidget)
        self.leNome.setObjectName("leNome")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leNome)
        self.lRG = QtGui.QLabel(self.formLayoutWidget)
        self.lRG.setObjectName("lRG")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lRG)
        self.leRG = QtGui.QLineEdit(self.formLayoutWidget)
        self.leRG.setObjectName("leRG")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leRG)
        self.lCPF = QtGui.QLabel(self.formLayoutWidget)
        self.lCPF.setObjectName("lCPF")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lCPF)
        self.leCPF = QtGui.QLineEdit(self.formLayoutWidget)
        self.leCPF.setObjectName("leCPF")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leCPF)
        self.lTelefone = QtGui.QLabel(self.formLayoutWidget)
        self.lTelefone.setObjectName("lTelefone")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lTelefone)
        self.leTelefone = QtGui.QLineEdit(self.formLayoutWidget)
        self.leTelefone.setObjectName("leTelefone")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leTelefone)
        self.lUsuario = QtGui.QLabel(self.formLayoutWidget)
        self.lUsuario.setObjectName("lUsuario")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lUsuario)
        self.leUsuario = QtGui.QLineEdit(self.formLayoutWidget)
        self.leUsuario.setObjectName("leUsuario")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.leUsuario)
        self.lSenha = QtGui.QLabel(self.formLayoutWidget)
        self.lSenha.setObjectName("lSenha")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lSenha)
        self.leSenha = QtGui.QLineEdit(self.formLayoutWidget)
        self.leSenha.setObjectName("leSenha")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.leSenha)
        self.lConfirmar = QtGui.QLabel(self.formLayoutWidget)
        self.lConfirmar.setObjectName("lConfirmar")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lConfirmar)
        self.leConfirmar = QtGui.QLineEdit(self.formLayoutWidget)
        self.leConfirmar.setObjectName("leConfirmar")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.leConfirmar)
        self.bbCancelarOK = QtGui.QDialogButtonBox(self.formLayoutWidget)
        self.bbCancelarOK.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbCancelarOK.setObjectName("bbCancelarOK")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.bbCancelarOK)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.lNome.setText(kdecore.i18n("Nome"))
        self.lRG.setText(kdecore.i18n("RG"))
        self.lCPF.setText(kdecore.i18n("CPF"))
        self.lTelefone.setText(kdecore.i18n("Telefone"))
        self.lUsuario.setText(kdecore.i18n("Usuario"))
        self.lSenha.setText(kdecore.i18n("Senha"))
        self.lConfirmar.setText(kdecore.i18n("Confirmar senha"))

