#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from userIndex.ui on Thu Nov 24 20:26:05 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 699)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.list_2 = QtGui.QTreeWidget(self.splitter)
        self.list_2.setTabKeyNavigation(True)
        self.list_2.setAlternatingRowColors(True)
        self.list_2.setItemsExpandable(False)
        self.list_2.setExpandsOnDoubleClick(False)
        self.list_2.setObjectName("list_2")
        self.product_form = userForm(self.splitter)
        self.product_form.setObjectName("product_form")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.pushButton.setText(kdecore.i18n("Novo Usuario"))
        self.pushButton_2.setText(kdecore.i18n("Editar Usuario"))
        self.pushButton_3.setText(kdecore.i18n("Excluir Usuario"))
        self.list_2.setSortingEnabled(True)
        self.list_2.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.list_2.headerItem().setText(1, kdecore.i18n("Nome"))
        self.list_2.headerItem().setText(2, kdecore.i18n("Forncedor"))
        self.list_2.headerItem().setText(3, kdecore.i18n("Preco"))
        self.list_2.headerItem().setText(4, kdecore.i18n("Quantidade"))

from userform import userForm
