#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from sellsIndex.ui on Thu Nov 24 21:15:35 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(664, 333)
        self.sells_index = QtGui.QTreeWidget(Form)
        self.sells_index.setGeometry(QtCore.QRect(6, 10, 651, 315))
        self.sells_index.setObjectName("sells_index")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.sells_index.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.sells_index.headerItem().setText(1, kdecore.i18n("Nome"))
        self.sells_index.headerItem().setText(2, kdecore.i18n("Preco"))
        self.sells_index.headerItem().setText(3, kdecore.i18n("Quantidade"))
        self.sells_index.headerItem().setText(4, kdecore.i18n("Total"))

