#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from mainWindow.ui on Mon Nov 28 15:44:57 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 705)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.provider_tab = QtGui.QWidget()
        self.provider_tab.setObjectName("provider_tab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.provider_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.provider_mng = ProviderIndex(self.provider_tab)
        self.provider_mng.setObjectName("provider_mng")
        self.horizontalLayout_3.addWidget(self.provider_mng)
        self.tabWidget.addTab(self.provider_tab, "")
        self.product_tab = QtGui.QWidget()
        self.product_tab.setObjectName("product_tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.product_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.product_mng = ProductIndex(self.product_tab)
        self.product_mng.setObjectName("product_mng")
        self.horizontalLayout_2.addWidget(self.product_mng)
        self.tabWidget.addTab(self.product_tab, "")
        self.sell_tab = QtGui.QWidget()
        self.sell_tab.setObjectName("sell_tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.sell_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_sell = SellForm(self.sell_tab)
        self.new_sell.setObjectName("new_sell")
        self.horizontalLayout.addWidget(self.new_sell)
        self.tabWidget.addTab(self.sell_tab, "")
        self.new_sell_tab = QtGui.QWidget()
        self.new_sell_tab.setObjectName("new_sell_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.new_sell_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sell_mng = SellIndex(self.new_sell_tab)
        self.sell_mng.setObjectName("sell_mng")
        self.verticalLayout_3.addWidget(self.sell_mng)
        self.tabWidget.addTab(self.new_sell_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.new_sell, QtCore.SIGNAL("sell_changed()"), self.sell_mng.refresh)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(kdecore.i18n("MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.provider_tab), kdecore.i18n("Fornecedor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.product_tab), kdecore.i18n("Produto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sell_tab), kdecore.i18n("Vender"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.new_sell_tab), kdecore.i18n("Vendas"))

from sellIndex import SellIndex
from productIndex import ProductIndex
from providerIndex import ProviderIndex
from sellForm import SellForm
