#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from productIndex.ui on Mon Nov 28 15:44:57 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 683)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botton_new = QtGui.QPushButton(Form)
        self.botton_new.setObjectName("botton_new")
        self.horizontalLayout.addWidget(self.botton_new)
        self.button_edit = QtGui.QPushButton(Form)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.button_delete = QtGui.QPushButton(Form)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.product_index = QtGui.QTreeWidget(self.splitter)
        self.product_index.setTabKeyNavigation(True)
        self.product_index.setAlternatingRowColors(True)
        self.product_index.setItemsExpandable(False)
        self.product_index.setExpandsOnDoubleClick(False)
        self.product_index.setObjectName("product_index")
        self.product_form = ProductForm(self.splitter)
        self.product_form.setObjectName("product_form")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.botton_new, QtCore.SIGNAL("clicked()"), Form.new)
        QtCore.QObject.connect(self.button_edit, QtCore.SIGNAL("clicked()"), Form.remove)
        QtCore.QObject.connect(self.button_delete, QtCore.SIGNAL("clicked()"), Form.edit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.botton_new.setText(kdecore.i18n("Novo Produto"))
        self.button_edit.setText(kdecore.i18n("Apagar Produto"))
        self.button_delete.setText(kdecore.i18n("Editar Produto"))
        self.product_index.setSortingEnabled(True)
        self.product_index.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.product_index.headerItem().setText(1, kdecore.i18n("Nome"))
        self.product_index.headerItem().setText(2, kdecore.i18n("Forncedor"))
        self.product_index.headerItem().setText(3, kdecore.i18n("Preco"))
        self.product_index.headerItem().setText(4, kdecore.i18n("Quantidade"))

from productForm import ProductForm
