#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from productForm.ui on Mon Nov 28 15:44:57 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 259)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 561, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.pidLabel = QtGui.QLabel(self.layoutWidget)
        self.pidLabel.setObjectName("pidLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pidLabel)
        self.nameLabel = QtGui.QLabel(self.layoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.fornLabel = QtGui.QLabel(self.layoutWidget)
        self.fornLabel.setObjectName("fornLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.fornLabel)
        self.priceLabel = QtGui.QLabel(self.layoutWidget)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.priceLabel)
        self.amountLabel = QtGui.QLabel(self.layoutWidget)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.amountLabel)
        self.pidText = QtGui.QLineEdit(self.layoutWidget)
        self.pidText.setEnabled(False)
        self.pidText.setObjectName("pidText")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.pidText)
        self.nameText = QtGui.QLineEdit(self.layoutWidget)
        self.nameText.setObjectName("nameText")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nameText)
        self.priceText = QtGui.QLineEdit(self.layoutWidget)
        self.priceText.setObjectName("priceText")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.priceText)
        self.amountText = QtGui.QLineEdit(self.layoutWidget)
        self.amountText.setObjectName("amountText")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.amountText)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.providerComboBox = QtGui.QComboBox(self.layoutWidget)
        self.providerComboBox.setObjectName("providerComboBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.providerComboBox)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Form.cancel)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Form.save)
        QtCore.QObject.connect(self.pidText, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.nameText, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.priceText, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.amountText, QtCore.SIGNAL("textChanged(QString)"), Form.reloadRow)
        QtCore.QObject.connect(self.providerComboBox, QtCore.SIGNAL("currentIndexChanged(int)"), Form.reloadRow)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.pidLabel.setText(kdecore.i18n("Codigo:"))
        self.nameLabel.setText(kdecore.i18n("Nome:"))
        self.fornLabel.setText(kdecore.i18n("Fornecedor:"))
        self.priceLabel.setText(kdecore.i18n("Preco:"))
        self.amountLabel.setText(kdecore.i18n("Quantidade:"))

