#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from providerIndex.ui on Mon Nov 28 15:44:58 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(587, 694)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.provider_index = QtGui.QTreeWidget(self.splitter)
        self.provider_index.setTabKeyNavigation(True)
        self.provider_index.setAlternatingRowColors(True)
        self.provider_index.setItemsExpandable(False)
        self.provider_index.setExpandsOnDoubleClick(False)
        self.provider_index.setObjectName("provider_index")
        self.provider_form = ProviderForm(self.splitter)
        self.provider_form.setObjectName("provider_form")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Form.new)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Form.remove)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Form.edit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.pushButton_3.setText(kdecore.i18n("Novo Fornecedor"))
        self.pushButton_2.setText(kdecore.i18n("Apagar Fornecedor"))
        self.pushButton.setText(kdecore.i18n("Editar Fornecedor"))
        self.provider_index.setSortingEnabled(True)
        self.provider_index.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.provider_index.headerItem().setText(1, kdecore.i18n("Nome"))
        self.provider_index.headerItem().setText(2, kdecore.i18n("Telefone"))

from providerForm import ProviderForm
