#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from sellIndex.ui on Mon Nov 28 15:44:58 2011
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 618)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botton_new_sell = QtGui.QPushButton(Form)
        self.botton_new_sell.setObjectName("botton_new_sell")
        self.horizontalLayout.addWidget(self.botton_new_sell)
        self.button_edit_sell = QtGui.QPushButton(Form)
        self.button_edit_sell.setObjectName("button_edit_sell")
        self.horizontalLayout.addWidget(self.button_edit_sell)
        self.button_delete_sell = QtGui.QPushButton(Form)
        self.button_delete_sell.setObjectName("button_delete_sell")
        self.horizontalLayout.addWidget(self.button_delete_sell)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sell_index = QtGui.QTreeWidget(Form)
        self.sell_index.setAnimated(False)
        self.sell_index.setObjectName("sell_index")
        self.verticalLayout.addWidget(self.sell_index)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.botton_new_sell, QtCore.SIGNAL("clicked()"), Form.new)
        QtCore.QObject.connect(self.button_edit_sell, QtCore.SIGNAL("clicked()"), Form.remove)
        QtCore.QObject.connect(self.button_delete_sell, QtCore.SIGNAL("clicked()"), Form.edit)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(kdecore.i18n("Form"))
        self.botton_new_sell.setText(kdecore.i18n("Nova venda"))
        self.button_edit_sell.setText(kdecore.i18n("Apagar venda"))
        self.button_delete_sell.setText(kdecore.i18n("Editar venda"))
        self.sell_index.setSortingEnabled(False)
        self.sell_index.headerItem().setText(0, kdecore.i18n("Codigo"))
        self.sell_index.headerItem().setText(1, kdecore.i18n("Nome"))
        self.sell_index.headerItem().setText(2, kdecore.i18n("Preco"))

